[build]
  publish = "public"  
  command = "git config core.quotepath false && hugo --gc --minify"

[build.environment]
  GO_VERSION = "1.24.2"
  HUGO_VERSION = "0.147.1"
  NODE_VERSION = "22"
  TZ = "America/Los_Angeles"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
